networks:
  aqa-network:
    name: aqa-network
    driver: bridge

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: jnhbgvfc
      POSTGRES_DB: aqa
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    networks:
      - aqa-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: hoanghy/aqa-backend
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=jnhbgvfc
      - DB_DATABASE=aqa
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - aqa-network

volumes:
  postgresql-volume:


